name: build-docker

on: [push]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: List files
        run: ls -la

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t bapju/getting-started-app .

      - name: List Docker images
        run: docker images

      - name: Push Docker image
        run: docker push bapju/getting-started-app

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file .github/workflows/cloudformation/template.yaml \
            --stack-name gp8-tp4 \
            --capabilities CAPABILITY_NAMED_IAM
